export const hotelsTypes = {
  FETCH_HOTELS_REQUEST: 'FETCH_HOTELS_REQUEST',
  FETCH_HOTELS_SUCCESS: 'FETCH_HOTELS_SUCCESS',
  FETCH_HOTELS_FAILURE: 'FETCH_HOTELS_FAILURE',
};

export const userTypes = {
    SET_USER: 'SET_USER',
    SET_FAVORITE_HOTELS: 'SET_FAVORITE_HOTELS',
    UNSET_FAVORITE_HOTELS: 'UNSET_FAVORITE_HOTELS',
    FILTER_BY_STARS: 'FILTER_BY_STARS',
    FILTER_BY_PRICE: 'FILTER_BY_PRICE',
    RESET_FILTER: 'RESET_FILTER',
  }
